name: 'Nightly Merge'

on:
  push:
    branches:
      - main

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
  
    - name: Mark github workspace as safe
      run: |
          git config --global --add safe.directory '*'

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'main'
        development_branch: 'first-commit'
        allow_ff: false
        allow_forks: true
      env:
        GITHUB_TOKEN: ${{ secrets.DUMMY_TOKEN }}

