name: Merge Master to Feature Branch
on: 
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-master-back-to-feature-branch:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      with:
          github_token: ${{secrets.DUMMY_TOKEN}}
      run: |
          git config --local user.email "mrinalpr1998@gmail.com"
          git config --local user.name "mrinalpravi"
    - name: Merge master back to Features/RCP
      run: |
          git fetch --unshallow
          git checkout feature
          git pull
          git merge --no-ff main -m "Auto-merge main back to feature"
          git push