name: Running Dummy Commands

on:
  push:
    branches: [ main ]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        github_token: ${{secrets.DUMMY_TOKEN}}
    - name: git
      run: |
        git --version
        git config user.name "mrinalpravi"
        git config user.email "mrinalpr1998@gmail.com"
        git status
        git fetch origin main
        git pull
        git checkout feature
        git merge main
        git status
